name: KqueueCI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: ['4.11.0', '4.10.1' , '4.09.1', '4.08.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: Install dependencies
        run: |
          opam pin add kqueue.dev -n .
          opam depext -yt kqueue
          opam install -t . --deps-only
      - name: Build
        run: |
          opam exec -- dune build
